name: Main branch workflow
run-name: Main Workflow
on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v3 
      
      - name: Setup node version
        - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn;

      - name: Unit tests
        run: yarn test;

      - name: Functional Tests
        run: yarn test:e2e;

      - name: Building project
          yarn build;
