name: Main branch workflow
run-name: Main Workflow
on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout code'
        uses: actions/checkout@v3 
      
      - name: 'Run docker compose up'
        run: docker-compose up -d

      - name: 'Access the backend container'
        run: docker exec -it todo-backend bash;

      - name: 'Unit tests'
        run: yarn test;

      - name: 'Functional Tests'
        run: yarn test:e2e;

      - name: 'Building project'
        run: yarn build;
