name: Main branch workflow
run-name: Main Workflow
on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout code'
        uses: actions/checkout@v3 
      
      - name: 'Run docker compose up to setup the database'
        run: docker-compose up -d database;

      - name: 'Building backend image'
        run: docker-compose build backend;

      - name: 'Running unit tests on backend container'
        run: docker-compose run backend yarn test;

      - name: 'Running functional Tests on backend container'
        run: docker-compose run backend yarn test:e2e;

      - name: 'Building project on backend container'
        run: docker-compose run backend yarn build;
