name: Main branch workflow
run-name: Main Workflow
on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout code'
        uses: actions/checkout@v3 
      
      - name: 'Run docker compose up to setup the database'
        run: docker-compose up -d database;

      - name: 'Running Tests on backend test container'
        run: docker-compose run --rm backend-test;

