name: Main branch workflow
run-name: Main Workflow
on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout code'
        uses: actions/checkout@v3 
      
      - name: 'Run docker compose up'
        run: docker-compose up -d;

      - name: 'Running unit tests on backend container'
        run: docker exec todo-backend yarn test;

      - name: 'Running functional Tests on backend container'
        run: docker exec yarn test:e2e;

      - name: 'Building project on backend container'
        run: yarn build;
