name: Main branch workflow
run-name: Main Workflow
on:
  push:
    branches:
      - main 

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3 
      
      - name: 'Running Tests on backend test container'
        run: docker-compose -f docker-compose.test.yaml up;

